GET http://localhost:8080/users/7e51313a-d5dd-432f-b01f-54efb9a48f0e
Accept: application/json

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "usuario@mail.com",
  "password": "12345aBc",
  "fullName": "Usuario de Prueba",
  "dateBirth": "1990-05-12"
}

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "usuario2@mail.com",
  "password": "12345aBc",
  "fullName": "Usuario de Prueba 2",
  "dateBirth": "1990-05-12"
}

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "usuario3@mail.com",
  "password": "12345aBc",
  "fullName": "Usuario de Prueba 3",
  "dateBirth": "1990-05-13"
}


### Envío con fallas en la solicitud
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "usuariomail.com",
  "fullName": "Usuario de Prueba",
  "dateBirth": "1990-05-12"
}

###
